### PR TITLE
Add the CFGLock EFI tool 

### PR DESCRIPTION
**Pull request by nearlynogravitas**
This allows for easily disabling the CFG lock.  Just one press of a key does it.

To enable the tool, set

```
<key>Enabled</key>
<true/>
```

When you boot and reach the OpenCore menu, select CFGLock.  Then toggle the CFG lock on or off using the key indicated on screen.

See also

- https://dortania.github.io/OpenCore-Desktop-Guide/extras/msr-lock.html
- https://www.youtube.com/watch?v=W4JXVNJsK98

### CODE REVIEW

**Comment by nearlynogravitas** [comment]
I found the CFGLock.EFI file at https://www.hackintosh-forum.de/forum/thread/48751-cfg-lock/

**Comment by cmer** [comment]
Great pull request, thanks! I'm kinda bummed that this EFI made my video tutorial useless, I spent so much time on it! 😆

**Comment by nearlynogravitas** [comment]
You're welcome!

Your video was well done.  If you made more hackintosh videos like that one, I think people would watch them.  You should post your [BIOS video](https://www.youtube.com/watch?v=-cMrL1mXGZM) to [/r/hackintosh](https://www.reddit.com/r/hackintosh).  A lot of people use that motherboard, but not sp many people post their BIOS setup.

**Comment by cmer** [comment]
Good idea. I'll do that :)

**Pull request merged**
